### ISSUE TITLE
Changing symfony project language to "en" brings error

### ISSUE THREAD

**Issue by petermarl** [flowfusion/blog-bundle#6]
I've changed the language in `config.yml` from `de` to `en` and got the following error message:

`An exception has been thrown during the rendering of a template ("Notice: Undefined index: english").`

It looks like an bug in `SlugifyService`.

**Comment by antondachauer** [comment]
Thanks for reporting this bug, I just fixed it.

Maybe you have to clear the symfony cache to get it working.
